# https://blog.questionable.services/article/build-go-binaries-travis-ci-github/
language: go
sudo: false
matrix:
  include:
    - go: 1.11.x
      env: LATEST=true 

before_install:
  - go get github.com/mitchellh/gox

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet $(go list ./... | grep -v /vendor/)
  - go test -v -race ./...
  # Only build binaries from the latest Go release.
  - if [ "${LATEST}" = "true" ]; then ./build_bin.sh; fi