// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package rpi

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VersionRes struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionRes) Reset()         { *m = VersionRes{} }
func (m *VersionRes) String() string { return proto.CompactTextString(m) }
func (*VersionRes) ProtoMessage()    {}
func (*VersionRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *VersionRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionRes.Unmarshal(m, b)
}
func (m *VersionRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionRes.Marshal(b, m, deterministic)
}
func (m *VersionRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionRes.Merge(m, src)
}
func (m *VersionRes) XXX_Size() int {
	return xxx_messageInfo_VersionRes.Size(m)
}
func (m *VersionRes) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionRes.DiscardUnknown(m)
}

var xxx_messageInfo_VersionRes proto.InternalMessageInfo

func (m *VersionRes) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*VersionRes)(nil), "rpi.VersionRes")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 118 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x2a, 0xc8, 0x94, 0xe2, 0x4a,
	0x4a, 0x2c, 0x4e, 0x85, 0x08, 0x28, 0xa9, 0x71, 0x71, 0x85, 0xa5, 0x16, 0x15, 0x67, 0xe6, 0xe7,
	0x05, 0xa5, 0x16, 0x0b, 0x49, 0x70, 0xb1, 0x97, 0x41, 0x78, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c,
	0x41, 0x30, 0xae, 0x91, 0x21, 0x17, 0x9b, 0x33, 0xd8, 0x20, 0x21, 0x75, 0x2e, 0x76, 0xa8, 0x0e,
	0x21, 0x4e, 0xbd, 0xa2, 0x82, 0x4c, 0xbd, 0xb0, 0xfc, 0xcc, 0x14, 0x29, 0x7e, 0x08, 0x13, 0x6e,
	0x94, 0x12, 0x43, 0x12, 0x1b, 0xd8, 0x06, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x16, 0x59,
	0x23, 0x08, 0x82, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommonClient is the client API for Common service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommonClient interface {
	Version(ctx context.Context, in *Void, opts ...grpc.CallOption) (*VersionRes, error)
}

type commonClient struct {
	cc *grpc.ClientConn
}

func NewCommonClient(cc *grpc.ClientConn) CommonClient {
	return &commonClient{cc}
}

func (c *commonClient) Version(ctx context.Context, in *Void, opts ...grpc.CallOption) (*VersionRes, error) {
	out := new(VersionRes)
	err := c.cc.Invoke(ctx, "/rpi.Common/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommonServer is the server API for Common service.
type CommonServer interface {
	Version(context.Context, *Void) (*VersionRes, error)
}

func RegisterCommonServer(s *grpc.Server, srv CommonServer) {
	s.RegisterService(&_Common_serviceDesc, srv)
}

func _Common_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpi.Common/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonServer).Version(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

var _Common_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpi.Common",
	HandlerType: (*CommonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _Common_Version_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common.proto",
}
