// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gpio.proto

package rpi

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InitReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitReq) Reset()         { *m = InitReq{} }
func (m *InitReq) String() string { return proto.CompactTextString(m) }
func (*InitReq) ProtoMessage()    {}
func (*InitReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59fedb88b556689a, []int{0}
}

func (m *InitReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitReq.Unmarshal(m, b)
}
func (m *InitReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitReq.Marshal(b, m, deterministic)
}
func (m *InitReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitReq.Merge(m, src)
}
func (m *InitReq) XXX_Size() int {
	return xxx_messageInfo_InitReq.Size(m)
}
func (m *InitReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InitReq.DiscardUnknown(m)
}

var xxx_messageInfo_InitReq proto.InternalMessageInfo

type CloseReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseReq) Reset()         { *m = CloseReq{} }
func (m *CloseReq) String() string { return proto.CompactTextString(m) }
func (*CloseReq) ProtoMessage()    {}
func (*CloseReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59fedb88b556689a, []int{1}
}

func (m *CloseReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseReq.Unmarshal(m, b)
}
func (m *CloseReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseReq.Marshal(b, m, deterministic)
}
func (m *CloseReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseReq.Merge(m, src)
}
func (m *CloseReq) XXX_Size() int {
	return xxx_messageInfo_CloseReq.Size(m)
}
func (m *CloseReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseReq.DiscardUnknown(m)
}

var xxx_messageInfo_CloseReq proto.InternalMessageInfo

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_59fedb88b556689a, []int{2}
}

func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (m *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(m, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

type SetDirectionReq struct {
	Pin                  string   `protobuf:"bytes,1,opt,name=pin,proto3" json:"pin,omitempty"`
	Direction            int32    `protobuf:"varint,2,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetDirectionReq) Reset()         { *m = SetDirectionReq{} }
func (m *SetDirectionReq) String() string { return proto.CompactTextString(m) }
func (*SetDirectionReq) ProtoMessage()    {}
func (*SetDirectionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59fedb88b556689a, []int{3}
}

func (m *SetDirectionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDirectionReq.Unmarshal(m, b)
}
func (m *SetDirectionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDirectionReq.Marshal(b, m, deterministic)
}
func (m *SetDirectionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDirectionReq.Merge(m, src)
}
func (m *SetDirectionReq) XXX_Size() int {
	return xxx_messageInfo_SetDirectionReq.Size(m)
}
func (m *SetDirectionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDirectionReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetDirectionReq proto.InternalMessageInfo

func (m *SetDirectionReq) GetPin() string {
	if m != nil {
		return m.Pin
	}
	return ""
}

func (m *SetDirectionReq) GetDirection() int32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

type PinInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Alias                []string `protobuf:"bytes,2,rep,name=alias,proto3" json:"alias,omitempty"`
	Caps                 int32    `protobuf:"varint,3,opt,name=caps,proto3" json:"caps,omitempty"`
	DigitalLogical       int32    `protobuf:"varint,4,opt,name=digitalLogical,proto3" json:"digitalLogical,omitempty"`
	AnalogLogical        int32    `protobuf:"varint,5,opt,name=analogLogical,proto3" json:"analogLogical,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PinInfo) Reset()         { *m = PinInfo{} }
func (m *PinInfo) String() string { return proto.CompactTextString(m) }
func (*PinInfo) ProtoMessage()    {}
func (*PinInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_59fedb88b556689a, []int{4}
}

func (m *PinInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PinInfo.Unmarshal(m, b)
}
func (m *PinInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PinInfo.Marshal(b, m, deterministic)
}
func (m *PinInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PinInfo.Merge(m, src)
}
func (m *PinInfo) XXX_Size() int {
	return xxx_messageInfo_PinInfo.Size(m)
}
func (m *PinInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PinInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PinInfo proto.InternalMessageInfo

func (m *PinInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PinInfo) GetAlias() []string {
	if m != nil {
		return m.Alias
	}
	return nil
}

func (m *PinInfo) GetCaps() int32 {
	if m != nil {
		return m.Caps
	}
	return 0
}

func (m *PinInfo) GetDigitalLogical() int32 {
	if m != nil {
		return m.DigitalLogical
	}
	return 0
}

func (m *PinInfo) GetAnalogLogical() int32 {
	if m != nil {
		return m.AnalogLogical
	}
	return 0
}

type PinsRes struct {
	Info                 []*PinInfo `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PinsRes) Reset()         { *m = PinsRes{} }
func (m *PinsRes) String() string { return proto.CompactTextString(m) }
func (*PinsRes) ProtoMessage()    {}
func (*PinsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_59fedb88b556689a, []int{5}
}

func (m *PinsRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PinsRes.Unmarshal(m, b)
}
func (m *PinsRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PinsRes.Marshal(b, m, deterministic)
}
func (m *PinsRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PinsRes.Merge(m, src)
}
func (m *PinsRes) XXX_Size() int {
	return xxx_messageInfo_PinsRes.Size(m)
}
func (m *PinsRes) XXX_DiscardUnknown() {
	xxx_messageInfo_PinsRes.DiscardUnknown(m)
}

var xxx_messageInfo_PinsRes proto.InternalMessageInfo

func (m *PinsRes) GetInfo() []*PinInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type DigitalWriteReq struct {
	Pin                  string   `protobuf:"bytes,1,opt,name=pin,proto3" json:"pin,omitempty"`
	Value                int32    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DigitalWriteReq) Reset()         { *m = DigitalWriteReq{} }
func (m *DigitalWriteReq) String() string { return proto.CompactTextString(m) }
func (*DigitalWriteReq) ProtoMessage()    {}
func (*DigitalWriteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59fedb88b556689a, []int{6}
}

func (m *DigitalWriteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DigitalWriteReq.Unmarshal(m, b)
}
func (m *DigitalWriteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DigitalWriteReq.Marshal(b, m, deterministic)
}
func (m *DigitalWriteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DigitalWriteReq.Merge(m, src)
}
func (m *DigitalWriteReq) XXX_Size() int {
	return xxx_messageInfo_DigitalWriteReq.Size(m)
}
func (m *DigitalWriteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DigitalWriteReq.DiscardUnknown(m)
}

var xxx_messageInfo_DigitalWriteReq proto.InternalMessageInfo

func (m *DigitalWriteReq) GetPin() string {
	if m != nil {
		return m.Pin
	}
	return ""
}

func (m *DigitalWriteReq) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type DigitalReadReq struct {
	Pin                  string   `protobuf:"bytes,1,opt,name=pin,proto3" json:"pin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DigitalReadReq) Reset()         { *m = DigitalReadReq{} }
func (m *DigitalReadReq) String() string { return proto.CompactTextString(m) }
func (*DigitalReadReq) ProtoMessage()    {}
func (*DigitalReadReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59fedb88b556689a, []int{7}
}

func (m *DigitalReadReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DigitalReadReq.Unmarshal(m, b)
}
func (m *DigitalReadReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DigitalReadReq.Marshal(b, m, deterministic)
}
func (m *DigitalReadReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DigitalReadReq.Merge(m, src)
}
func (m *DigitalReadReq) XXX_Size() int {
	return xxx_messageInfo_DigitalReadReq.Size(m)
}
func (m *DigitalReadReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DigitalReadReq.DiscardUnknown(m)
}

var xxx_messageInfo_DigitalReadReq proto.InternalMessageInfo

func (m *DigitalReadReq) GetPin() string {
	if m != nil {
		return m.Pin
	}
	return ""
}

type DigitalReadRes struct {
	Value                int32    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DigitalReadRes) Reset()         { *m = DigitalReadRes{} }
func (m *DigitalReadRes) String() string { return proto.CompactTextString(m) }
func (*DigitalReadRes) ProtoMessage()    {}
func (*DigitalReadRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_59fedb88b556689a, []int{8}
}

func (m *DigitalReadRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DigitalReadRes.Unmarshal(m, b)
}
func (m *DigitalReadRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DigitalReadRes.Marshal(b, m, deterministic)
}
func (m *DigitalReadRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DigitalReadRes.Merge(m, src)
}
func (m *DigitalReadRes) XXX_Size() int {
	return xxx_messageInfo_DigitalReadRes.Size(m)
}
func (m *DigitalReadRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DigitalReadRes.DiscardUnknown(m)
}

var xxx_messageInfo_DigitalReadRes proto.InternalMessageInfo

func (m *DigitalReadRes) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*InitReq)(nil), "rpi.InitReq")
	proto.RegisterType((*CloseReq)(nil), "rpi.CloseReq")
	proto.RegisterType((*Void)(nil), "rpi.Void")
	proto.RegisterType((*SetDirectionReq)(nil), "rpi.SetDirectionReq")
	proto.RegisterType((*PinInfo)(nil), "rpi.PinInfo")
	proto.RegisterType((*PinsRes)(nil), "rpi.PinsRes")
	proto.RegisterType((*DigitalWriteReq)(nil), "rpi.DigitalWriteReq")
	proto.RegisterType((*DigitalReadReq)(nil), "rpi.DigitalReadReq")
	proto.RegisterType((*DigitalReadRes)(nil), "rpi.DigitalReadRes")
}

func init() { proto.RegisterFile("gpio.proto", fileDescriptor_59fedb88b556689a) }

var fileDescriptor_59fedb88b556689a = []byte{
	// 369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0x6d, 0xfe, 0xb5, 0xbf, 0x4c, 0xfb, 0x6b, 0x65, 0xec, 0x21, 0x14, 0xd1, 0xb8, 0x48, 0x09,
	0x08, 0x85, 0xd6, 0x53, 0x8f, 0x62, 0x41, 0x0a, 0x82, 0x65, 0x05, 0x3d, 0xaf, 0xcd, 0x36, 0x0c,
	0x84, 0x6c, 0x9a, 0x44, 0xbf, 0x84, 0x27, 0xbf, 0xb1, 0x64, 0x9b, 0xda, 0x34, 0xd4, 0xdb, 0xec,
	0xcc, 0x7b, 0xb3, 0x33, 0xef, 0x0d, 0x40, 0x94, 0x92, 0x9a, 0xa4, 0x99, 0x2a, 0x14, 0x5a, 0x59,
	0x4a, 0xcc, 0x85, 0xce, 0x32, 0xa1, 0x82, 0xcb, 0x2d, 0x03, 0xf8, 0xf7, 0x10, 0xab, 0x5c, 0x96,
	0x71, 0x1b, 0xec, 0x57, 0x45, 0x21, 0xbb, 0x87, 0xc1, 0x8b, 0x2c, 0x16, 0x94, 0xc9, 0x75, 0x41,
	0x2a, 0xe1, 0x72, 0x8b, 0x67, 0x60, 0xa5, 0x94, 0x78, 0x86, 0x6f, 0x04, 0x2e, 0x2f, 0x43, 0xbc,
	0x00, 0x37, 0xdc, 0x23, 0x3c, 0xd3, 0x37, 0x02, 0x87, 0x1f, 0x12, 0xec, 0xdb, 0x80, 0xce, 0x8a,
	0x92, 0x65, 0xb2, 0x51, 0xd8, 0x07, 0x93, 0xc2, 0x8a, 0x6a, 0x52, 0x88, 0x43, 0x70, 0x44, 0x4c,
	0x22, 0xf7, 0x4c, 0xdf, 0x0a, 0x5c, 0xbe, 0x7b, 0x20, 0x82, 0xbd, 0x16, 0x69, 0xee, 0x59, 0xba,
	0x95, 0x8e, 0x71, 0x0c, 0xfd, 0x90, 0x22, 0x2a, 0x44, 0xfc, 0xa4, 0x22, 0x5a, 0x8b, 0xd8, 0xb3,
	0x75, 0xb5, 0x91, 0xc5, 0x1b, 0xf8, 0x2f, 0x12, 0x11, 0xab, 0x68, 0x0f, 0x73, 0x34, 0xec, 0x38,
	0xc9, 0x6e, 0xf5, 0x48, 0x39, 0x97, 0x39, 0xfa, 0x60, 0x53, 0xb2, 0x51, 0x9e, 0xe1, 0x5b, 0x41,
	0x77, 0xd6, 0x9b, 0x64, 0x29, 0x4d, 0xaa, 0x71, 0xb9, 0xae, 0xb0, 0x39, 0x0c, 0x16, 0xbb, 0x4f,
	0xde, 0x32, 0x2a, 0xe4, 0x69, 0x0d, 0x86, 0xe0, 0x7c, 0x8a, 0xf8, 0x43, 0x56, 0xfb, 0xef, 0x1e,
	0x8c, 0x41, 0xbf, 0xa2, 0x72, 0x29, 0xc2, 0x93, 0x4c, 0x36, 0x6e, 0x60, 0xf2, 0x43, 0x2f, 0xa3,
	0xd6, 0x6b, 0xf6, 0x65, 0x82, 0xfd, 0xb8, 0x5a, 0x3e, 0xe3, 0x25, 0xd8, 0xa5, 0x65, 0xe8, 0xea,
	0x59, 0x4b, 0x9b, 0x46, 0x87, 0x90, 0xb5, 0xf0, 0x0a, 0x1c, 0xed, 0xe3, 0x9f, 0x80, 0x6b, 0xb0,
	0xcb, 0xed, 0xeb, 0xf5, 0xdf, 0xbd, 0x4b, 0x4d, 0x58, 0x0b, 0xa7, 0xd0, 0xab, 0xfb, 0x8e, 0x43,
	0x5d, 0x6f, 0x9c, 0xc2, 0x71, 0xd7, 0x29, 0xf4, 0xea, 0x32, 0x55, 0x94, 0x86, 0x72, 0xc7, 0x94,
	0x39, 0x74, 0x6b, 0xab, 0xe3, 0x79, 0x9d, 0x51, 0x09, 0x36, 0x3a, 0x91, 0xcc, 0x59, 0xeb, 0xbd,
	0xad, 0x6f, 0xf8, 0xee, 0x27, 0x00, 0x00, 0xff, 0xff, 0x53, 0x79, 0x65, 0xca, 0xd1, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GPIOClient is the client API for GPIO service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GPIOClient interface {
	Init(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Void, error)
	Close(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Void, error)
	Pins(ctx context.Context, in *Void, opts ...grpc.CallOption) (*PinsRes, error)
	SetDirection(ctx context.Context, in *SetDirectionReq, opts ...grpc.CallOption) (*Void, error)
	DigitalWrite(ctx context.Context, in *DigitalWriteReq, opts ...grpc.CallOption) (*Void, error)
	DigitalRead(ctx context.Context, in *DigitalReadReq, opts ...grpc.CallOption) (*DigitalReadRes, error)
}

type gPIOClient struct {
	cc *grpc.ClientConn
}

func NewGPIOClient(cc *grpc.ClientConn) GPIOClient {
	return &gPIOClient{cc}
}

func (c *gPIOClient) Init(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/rpi.GPIO/Init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPIOClient) Close(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/rpi.GPIO/Close", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPIOClient) Pins(ctx context.Context, in *Void, opts ...grpc.CallOption) (*PinsRes, error) {
	out := new(PinsRes)
	err := c.cc.Invoke(ctx, "/rpi.GPIO/Pins", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPIOClient) SetDirection(ctx context.Context, in *SetDirectionReq, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/rpi.GPIO/SetDirection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPIOClient) DigitalWrite(ctx context.Context, in *DigitalWriteReq, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/rpi.GPIO/DigitalWrite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPIOClient) DigitalRead(ctx context.Context, in *DigitalReadReq, opts ...grpc.CallOption) (*DigitalReadRes, error) {
	out := new(DigitalReadRes)
	err := c.cc.Invoke(ctx, "/rpi.GPIO/DigitalRead", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GPIOServer is the server API for GPIO service.
type GPIOServer interface {
	Init(context.Context, *Void) (*Void, error)
	Close(context.Context, *Void) (*Void, error)
	Pins(context.Context, *Void) (*PinsRes, error)
	SetDirection(context.Context, *SetDirectionReq) (*Void, error)
	DigitalWrite(context.Context, *DigitalWriteReq) (*Void, error)
	DigitalRead(context.Context, *DigitalReadReq) (*DigitalReadRes, error)
}

func RegisterGPIOServer(s *grpc.Server, srv GPIOServer) {
	s.RegisterService(&_GPIO_serviceDesc, srv)
}

func _GPIO_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPIOServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpi.GPIO/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPIOServer).Init(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPIO_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPIOServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpi.GPIO/Close",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPIOServer).Close(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPIO_Pins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPIOServer).Pins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpi.GPIO/Pins",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPIOServer).Pins(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPIO_SetDirection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDirectionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPIOServer).SetDirection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpi.GPIO/SetDirection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPIOServer).SetDirection(ctx, req.(*SetDirectionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPIO_DigitalWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DigitalWriteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPIOServer).DigitalWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpi.GPIO/DigitalWrite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPIOServer).DigitalWrite(ctx, req.(*DigitalWriteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPIO_DigitalRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DigitalReadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPIOServer).DigitalRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpi.GPIO/DigitalRead",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPIOServer).DigitalRead(ctx, req.(*DigitalReadReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _GPIO_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpi.GPIO",
	HandlerType: (*GPIOServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _GPIO_Init_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _GPIO_Close_Handler,
		},
		{
			MethodName: "Pins",
			Handler:    _GPIO_Pins_Handler,
		},
		{
			MethodName: "SetDirection",
			Handler:    _GPIO_SetDirection_Handler,
		},
		{
			MethodName: "DigitalWrite",
			Handler:    _GPIO_DigitalWrite_Handler,
		},
		{
			MethodName: "DigitalRead",
			Handler:    _GPIO_DigitalRead_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gpio.proto",
}
