// Code generated by protoc-gen-go. DO NOT EDIT.
// source: picam.proto

package rpi

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResponseImage struct {
	ImageBytes           []byte   `protobuf:"bytes,1,opt,name=imageBytes,proto3" json:"imageBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseImage) Reset()         { *m = ResponseImage{} }
func (m *ResponseImage) String() string { return proto.CompactTextString(m) }
func (*ResponseImage) ProtoMessage()    {}
func (*ResponseImage) Descriptor() ([]byte, []int) {
	return fileDescriptor_30fec5ee6d2f922d, []int{0}
}

func (m *ResponseImage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseImage.Unmarshal(m, b)
}
func (m *ResponseImage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseImage.Marshal(b, m, deterministic)
}
func (m *ResponseImage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseImage.Merge(m, src)
}
func (m *ResponseImage) XXX_Size() int {
	return xxx_messageInfo_ResponseImage.Size(m)
}
func (m *ResponseImage) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseImage.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseImage proto.InternalMessageInfo

func (m *ResponseImage) GetImageBytes() []byte {
	if m != nil {
		return m.ImageBytes
	}
	return nil
}

func init() {
	proto.RegisterType((*ResponseImage)(nil), "rpi.ResponseImage")
}

func init() { proto.RegisterFile("picam.proto", fileDescriptor_30fec5ee6d2f922d) }

var fileDescriptor_30fec5ee6d2f922d = []byte{
	// 131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xc8, 0x4c, 0x4e,
	0xcc, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x2a, 0xc8, 0x94, 0xe2, 0x4a, 0x4a,
	0x2c, 0x4e, 0x85, 0x08, 0x28, 0xe9, 0x73, 0xf1, 0x06, 0xa5, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7,
	0x7a, 0xe6, 0x26, 0xa6, 0xa7, 0x0a, 0xc9, 0x71, 0x71, 0x65, 0x82, 0x18, 0x4e, 0x95, 0x25, 0xa9,
	0xc5, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x48, 0x22, 0x46, 0x26, 0x5c, 0xac, 0x01, 0x99,
	0xce, 0x89, 0xb9, 0x42, 0xda, 0x5c, 0x1c, 0xee, 0xa9, 0x25, 0x01, 0x19, 0x20, 0x63, 0x39, 0xf5,
	0x8a, 0x0a, 0x32, 0xf5, 0xc2, 0xf2, 0x33, 0x53, 0xa4, 0x84, 0xc0, 0x4c, 0x14, 0x33, 0x95, 0x18,
	0x92, 0xd8, 0xc0, 0xb6, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x59, 0x91, 0x9a, 0x8d,
	0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PiCamClient is the client API for PiCam service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PiCamClient interface {
	GetPhoto(ctx context.Context, in *Void, opts ...grpc.CallOption) (*ResponseImage, error)
}

type piCamClient struct {
	cc *grpc.ClientConn
}

func NewPiCamClient(cc *grpc.ClientConn) PiCamClient {
	return &piCamClient{cc}
}

func (c *piCamClient) GetPhoto(ctx context.Context, in *Void, opts ...grpc.CallOption) (*ResponseImage, error) {
	out := new(ResponseImage)
	err := c.cc.Invoke(ctx, "/rpi.PiCam/GetPhoto", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PiCamServer is the server API for PiCam service.
type PiCamServer interface {
	GetPhoto(context.Context, *Void) (*ResponseImage, error)
}

func RegisterPiCamServer(s *grpc.Server, srv PiCamServer) {
	s.RegisterService(&_PiCam_serviceDesc, srv)
}

func _PiCam_GetPhoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PiCamServer).GetPhoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpi.PiCam/GetPhoto",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PiCamServer).GetPhoto(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

var _PiCam_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpi.PiCam",
	HandlerType: (*PiCamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPhoto",
			Handler:    _PiCam_GetPhoto_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "picam.proto",
}
