// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package rpi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ResponseVersion struct {
	Revision             string   `protobuf:"bytes,1,opt,name=revision,proto3" json:"revision,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseVersion) Reset()         { *m = ResponseVersion{} }
func (m *ResponseVersion) String() string { return proto.CompactTextString(m) }
func (*ResponseVersion) ProtoMessage()    {}
func (*ResponseVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_619a0212bf9e5dbf, []int{0}
}
func (m *ResponseVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseVersion.Unmarshal(m, b)
}
func (m *ResponseVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseVersion.Marshal(b, m, deterministic)
}
func (dst *ResponseVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseVersion.Merge(dst, src)
}
func (m *ResponseVersion) XXX_Size() int {
	return xxx_messageInfo_ResponseVersion.Size(m)
}
func (m *ResponseVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseVersion.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseVersion proto.InternalMessageInfo

func (m *ResponseVersion) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

func (m *ResponseVersion) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type RequestModprobe struct {
	Module               string   `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestModprobe) Reset()         { *m = RequestModprobe{} }
func (m *RequestModprobe) String() string { return proto.CompactTextString(m) }
func (*RequestModprobe) ProtoMessage()    {}
func (*RequestModprobe) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_619a0212bf9e5dbf, []int{1}
}
func (m *RequestModprobe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestModprobe.Unmarshal(m, b)
}
func (m *RequestModprobe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestModprobe.Marshal(b, m, deterministic)
}
func (dst *RequestModprobe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestModprobe.Merge(dst, src)
}
func (m *RequestModprobe) XXX_Size() int {
	return xxx_messageInfo_RequestModprobe.Size(m)
}
func (m *RequestModprobe) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestModprobe.DiscardUnknown(m)
}

var xxx_messageInfo_RequestModprobe proto.InternalMessageInfo

func (m *RequestModprobe) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func init() {
	proto.RegisterType((*ResponseVersion)(nil), "rpi.ResponseVersion")
	proto.RegisterType((*RequestModprobe)(nil), "rpi.RequestModprobe")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommonClient is the client API for Common service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommonClient interface {
	GetVersion(ctx context.Context, in *Void, opts ...grpc.CallOption) (*ResponseVersion, error)
	Modprobe(ctx context.Context, in *RequestModprobe, opts ...grpc.CallOption) (*Void, error)
}

type commonClient struct {
	cc *grpc.ClientConn
}

func NewCommonClient(cc *grpc.ClientConn) CommonClient {
	return &commonClient{cc}
}

func (c *commonClient) GetVersion(ctx context.Context, in *Void, opts ...grpc.CallOption) (*ResponseVersion, error) {
	out := new(ResponseVersion)
	err := c.cc.Invoke(ctx, "/rpi.Common/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commonClient) Modprobe(ctx context.Context, in *RequestModprobe, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/rpi.Common/Modprobe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommonServer is the server API for Common service.
type CommonServer interface {
	GetVersion(context.Context, *Void) (*ResponseVersion, error)
	Modprobe(context.Context, *RequestModprobe) (*Void, error)
}

func RegisterCommonServer(s *grpc.Server, srv CommonServer) {
	s.RegisterService(&_Common_serviceDesc, srv)
}

func _Common_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpi.Common/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonServer).GetVersion(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _Common_Modprobe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestModprobe)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonServer).Modprobe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpi.Common/Modprobe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonServer).Modprobe(ctx, req.(*RequestModprobe))
	}
	return interceptor(ctx, in, info, handler)
}

var _Common_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpi.Common",
	HandlerType: (*CommonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _Common_GetVersion_Handler,
		},
		{
			MethodName: "Modprobe",
			Handler:    _Common_Modprobe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common.proto",
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_common_619a0212bf9e5dbf) }

var fileDescriptor_common_619a0212bf9e5dbf = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x2a, 0xc8, 0x94, 0xe2, 0x4a,
	0x4a, 0x2c, 0x4e, 0x85, 0x08, 0x28, 0xb9, 0x73, 0xf1, 0x07, 0xa5, 0x16, 0x17, 0xe4, 0xe7, 0x15,
	0xa7, 0x86, 0xa5, 0x16, 0x15, 0x67, 0xe6, 0xe7, 0x09, 0x49, 0x71, 0x71, 0x14, 0xa5, 0x96, 0x65,
	0x82, 0xd8, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x70, 0xbe, 0x90, 0x04, 0x17, 0x7b, 0x19,
	0x44, 0x99, 0x04, 0x13, 0x58, 0x0a, 0xc6, 0x55, 0xd2, 0x04, 0x19, 0x54, 0x58, 0x9a, 0x5a, 0x5c,
	0xe2, 0x9b, 0x9f, 0x52, 0x50, 0x94, 0x9f, 0x94, 0x2a, 0x24, 0xc6, 0xc5, 0x96, 0x9b, 0x9f, 0x52,
	0x9a, 0x93, 0x0a, 0x35, 0x06, 0xca, 0x33, 0xca, 0xe0, 0x62, 0x73, 0x06, 0x3b, 0x4a, 0x48, 0x9f,
	0x8b, 0xcb, 0x3d, 0xb5, 0x04, 0x66, 0x31, 0xa7, 0x5e, 0x51, 0x41, 0xa6, 0x5e, 0x58, 0x7e, 0x66,
	0x8a, 0x94, 0x08, 0x98, 0x89, 0xe6, 0x32, 0x25, 0x06, 0x21, 0x5d, 0x2e, 0x0e, 0xb8, 0xf1, 0x30,
	0x35, 0x28, 0x96, 0x4a, 0x21, 0x0c, 0x51, 0x62, 0x48, 0x62, 0x03, 0x7b, 0xd2, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0x5d, 0x33, 0xab, 0xa6, 0x05, 0x01, 0x00, 0x00,
}
